const GENERAL_ERROR = 500;
const GENERAL_ERROR_MESSAGE = 'Произошла ошибка';
const BAD_REQUEST = 400;
const STATUS_ALREADY_EXISTS = 409;
const STATUS_NOT_AUTHORIZED = 401;
const STATUS_FORBIDDEN = 403;
const ALREADY_EXISTS_MESSAGE = 'Пользователь уже существует';
const BAD_REQUEST_MESSAGE = 'Переданы некорректные данные';
const RESOURCE_NOT_FOUND = 404;
const RESOURCE_NOT_FOUND_MESSAGE = 'Неверный URL';
const USER_NOT_FOUND_MESSAGE = 'Пользователь с данным ID не найден';
const USERS_NOT_FOUND_MESSAGE = 'Пользователи не найдены';
const CARDS_NOT_FOUND_MESSAGE = 'Карточки не найдены';
const CARD_NOT_FOUND_MESSAGE = 'Карточка с указанным ID не найдена';
const CARD_DELETION_NOT_AUTHORIZED_MESSAGE = 'Попытка удаления чужой карточки';
const STATUS_OK_CREATED = 201;
const STATUS_OK = 200;
const SUCCESSFUL_AUTHORIZATION_MESSAGE = 'Успешная авторизация';
const SUCCESSFUL_LOGOUT_MESSAGE = 'Успешный выход из системы';
const JWT_TOKEN_EXPIRES = '7d';
const COOKIE_MAX_AGE = 3600000 * 24 * 7;
module.exports = {
  GENERAL_ERROR,
  GENERAL_ERROR_MESSAGE,
  RESOURCE_NOT_FOUND,
  RESOURCE_NOT_FOUND_MESSAGE,
  USER_NOT_FOUND_MESSAGE,
  USERS_NOT_FOUND_MESSAGE,
  CARDS_NOT_FOUND_MESSAGE,
  CARD_NOT_FOUND_MESSAGE,
  CARD_DELETION_NOT_AUTHORIZED_MESSAGE,
  STATUS_NOT_AUTHORIZED,
  BAD_REQUEST,
  STATUS_ALREADY_EXISTS,
  STATUS_FORBIDDEN,
  ALREADY_EXISTS_MESSAGE,
  BAD_REQUEST_MESSAGE,
  STATUS_OK_CREATED,
  STATUS_OK,
  SUCCESSFUL_AUTHORIZATION_MESSAGE,
  SUCCESSFUL_LOGOUT_MESSAGE,
  JWT_TOKEN_EXPIRES,
  COOKIE_MAX_AGE,
};
